  FROM node:20-alpine
  WORKDIR /www
  COPY package*.json ./
  COPY apps/client/package*.json ./apps/client/
  COPY packages/ui/package*.json ./packages/ui/
  COPY packages/shared/package*.json ./packages/shared/
  RUN npm install
  CMD ["npm", "run", "dev", "--" ,"--filter=@permello/client"]