# Copyright 2026 Eduardo Turcios. All rights reserved.
# Unauthorized use, reproduction, or distribution of this file is strictly prohibited.
"""replace phone with address fields

Revision ID: 638e8b9d7694
Revises: d0385c147983
Create Date: 2026-02-28 23:36:09.771874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '638e8b9d7694'
down_revision: Union[str, None] = 'd0385c147983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('street', sqlmodel.sql.sqltypes.AutoString(), server_default='', nullable=False))
    op.add_column('users', sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), server_default='', nullable=False))
    op.add_column('users', sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), server_default='', nullable=False))
    op.add_column('users', sa.Column('zip_code', sqlmodel.sql.sqltypes.AutoString(), server_default='', nullable=False))
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'zip_code')
    op.drop_column('users', 'state')
    op.drop_column('users', 'city')
    op.drop_column('users', 'street')
    # ### end Alembic commands ###
