server {
    listen 80;
    server_name www.127.0.0.1.nip.io;

    location / {
        proxy_pass http://client-dev:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}

server {
    listen 80;
    server_name app.127.0.0.1.nip.io;

    location / {
        proxy_pass http://dashboard-dev:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    location /api/ {
        proxy_pass http://server-dev:5000;
        proxy_set_header Host $host;
    }
}
