  FROM node:20-alpine
  WORKDIR /app
  COPY package*.json ./
  COPY apps/dashboard/package*.json ./apps/dashboard/
  COPY packages/ui/package*.json ./packages/ui/
  COPY packages/shared/package*.json ./packages/shared/
  RUN npm install
  CMD ["npm", "run", "dev", "--" ,"--filter=@permello/dashboard"]